name: Build app

on:
    workflow_dispatch: #opzione che fa innesacare il workflow manualmente
        inputs:
            branch:
                description: "inserisci il nome della branch"

jobs: 
  build:

    runs-on: windows-latest

    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"

      - name: Setup node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
        
      - name: install yarn
        run: npm install yarn

      - name: install dependencies 
        run: yarn install
    
      - name: build
        run: yarn build

      
    
    
      
      